# Generated by Django 5.0.4 on 2024-04-25 00:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stowawayapi', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='record',
            name='genres',
        ),
        migrations.RemoveField(
            model_name='record',
            name='image_url',
        ),
    ]
