# Generated by Django 5.0.4 on 2024-04-26 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stowawayapi', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='condition',
            field=models.CharField(choices=[('POOR', 'Poor'), ('FAIR', 'Fair'), ('GOOD', 'Good'), ('VERY_GOOD', 'Very Good'), ('NEAR_MINT', 'Near Mint')], default='GOOD', max_length=20),
        ),
    ]
